version: "3.7"

services:
  nginx:
    image: nginx:1.13
    volumes:
      - "./app:/var/www/html"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
      - "5000:5000"
      - "15000:15000"
    networks:
      - proxy

  php:
    build:
      context: ./php
    volumes:
      - "./app:/var/www/html"
    ports:
      - "9000:9000"
    environment:
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=lucas
      - RABBITMQ_PASS=rootUser
    networks:
      - proxy

  rabbitmq:
    build:
      context: ./rabbitmq
    environment:
      - RABBITMQ_CONFIG_FILE=/etc/rabbitmq/rabbitmq-custom
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log [{console,[{level,debug}]}] -setcookie myCookieSecretXCBSDFASDGASFG
      - RABBITMQ_NODENAME=rabbit@rabbitmq
    ports:
      - "5600:5672"
      - "15600:15672"
    networks:
      - proxy

networks:
  proxy:
    external: true